# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbea24d5909bc1e5787f65f9b80fdd6a7f84e71374bc665841eb77bab414cae399a76f046086a3e4008143e2fc12986cc17f690be1d039376551b71f2b7906b1

test:
  secret_key_base: b5e0649e6028ab009eab1b433e9cb50bc3ae05b07aef0967c0134fbdd3ecdf7450e1d3ace1befd08d8ab696a04b6cdf1a981c3b78d8210f70d70398f3d5d1c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
